//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProfilingAndRecordManagementSystemF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class axaDBEntities : DbContext
    {
        public axaDBEntities()
            : base("name=axaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientBeneficiary> ClientBeneficiaries { get; set; }
        public virtual DbSet<ClientPlan> ClientPlans { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<FinancialAdvisor> FinancialAdvisors { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
