//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProfilingAndRecordManagementSystemF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientBeneficiary
    {
        public long ID { get; set; }
        public long CLIENT_ID { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string BIRTHPLACE { get; set; }
        public string RELATIONSHIP { get; set; }
        public string OCCUPATION { get; set; }
        public double SHARE { get; set; }
    }
}
