//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProfilingAndRecordManagementSystemF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public long id { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string spouselastname { get; set; }
        public string spousefirstname { get; set; }
        public string spousemiddlename { get; set; }
        public string gender { get; set; }
        public string civilstatus { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string birthplace { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> weight { get; set; }
        public string residenceaddress { get; set; }
        public string cpnumber { get; set; }
        public string telephonenumber { get; set; }
        public string emailaddress { get; set; }
        public string occupation { get; set; }
        public Nullable<double> worksalary { get; set; }
        public Nullable<double> businessincome { get; set; }
        public Nullable<double> othersource { get; set; }
        public string companyname { get; set; }
        public string companyaddress { get; set; }
        public string companycontact { get; set; }
        public string natureofbusiness { get; set; }
        public string taxidnumber { get; set; }
        public string sss_gsis_number { get; set; }
        public string answersub1 { get; set; }
        public string answersub2 { get; set; }
        public string answersub3 { get; set; }
        public Nullable<long> addedby_userid { get; set; }
        public Nullable<long> financial_advisor_id { get; set; }
        public Nullable<int> plan_id { get; set; }
    }
}
