//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProfilingAndRecordManagementSystemF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientBeneficiaries = new HashSet<ClientBeneficiary>();
            this.ClientPlans = new HashSet<ClientPlan>();
        }
    
        public int client_id { get; set; }
        public Nullable<int> addedby_user_id { get; set; }
        public Nullable<int> FA_id { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string spouselastname { get; set; }
        public string spousefirstname { get; set; }
        public string spousemiddlename { get; set; }
        public string gender { get; set; }
        public string civilstatus { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string birthplace { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> weight { get; set; }
        public string residenceaddress { get; set; }
        public string cpnumber { get; set; }
        public string telephonenumber { get; set; }
        public string emailaddress { get; set; }
        public string occupation { get; set; }
        public Nullable<double> worksalary { get; set; }
        public Nullable<double> businessincome { get; set; }
        public Nullable<double> othersource { get; set; }
        public string companyname { get; set; }
        public string companyaddress { get; set; }
        public string companycontact { get; set; }
        public string natureofbusiness { get; set; }
        public string taxidnumber { get; set; }
        public string sss_gsis_number { get; set; }
        public string answersub1 { get; set; }
        public string answersub2 { get; set; }
        public string answersub3 { get; set; }
        public string id_path1 { get; set; }
        public string id_path2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientBeneficiary> ClientBeneficiaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPlan> ClientPlans { get; set; }
        public virtual FinancialAdvisor FinancialAdvisor { get; set; }
    }
}
