//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProfilingAndRecordManagementSystemF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientBeneficiary
    {
        public int beneficiary_id { get; set; }
        public int client_id { get; set; }
        public string fullname { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string birthplace { get; set; }
        public string relationship { get; set; }
        public string occupation { get; set; }
        public double share { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
