//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProfilingAndRecordManagementSystemF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialAdvisor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FinancialAdvisor()
        {
            this.Clients = new HashSet<Client>();
        }
    
        public int FA_id { get; set; }
        public string Code_Num { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public string B_Date { get; set; }
        public string Gender { get; set; }
        public string Contact_Num { get; set; }
        public string Email_Add { get; set; }
        public string Address { get; set; }
        public string id_path { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client> Clients { get; set; }
    }
}
